"""add goals table

Revision ID: 8f27e04a7fc1
Revises: 
Create Date: 2020-03-09 04:49:05.235974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f27e04a7fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_model_name'), 'goal_model', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_model_name'), table_name='goal_model')
    op.drop_table('goal_model')
    # ### end Alembic commands ###
